@rem Generated by wch-cmake.
@echo off
if not "%~1"=="" set "MRS2_ROOT=%~f1"
if not defined MRS2_ROOT (
  echo MRS2_ROOT is not set. Pass its path as the first argument or set it before activation. 1>&2
  exit /b 1
)
set "WCH_COMPONENT_ROOT=%MRS2_ROOT%\resources\app\resources\win32\components\WCH"
set "WCH_SELECTED_TOOLCHAIN_BIN=%WCH_COMPONENT_ROOT%\Toolchain\@TOOLCHAIN_NAME@\bin"
set "WCH_SELECTED_OPENOCD_BIN=%WCH_COMPONENT_ROOT%\OpenOCD\OpenOCD\bin"
set "WCH_COMPILER=%WCH_SELECTED_TOOLCHAIN_BIN%\@TOOL_PREFIX@gcc.exe"
if not exist "%WCH_COMPILER%" (
  echo WCH compiler not found: %WCH_COMPILER% 1>&2
  exit /b 1
)
if not exist "%WCH_SELECTED_OPENOCD_BIN%\openocd.exe" (
  echo WCH OpenOCD not found: %WCH_SELECTED_OPENOCD_BIN%\openocd.exe 1>&2
  exit /b 1
)
if /I not "%WCH_TOOLCHAIN_BIN%"=="%WCH_SELECTED_TOOLCHAIN_BIN%" set "PATH=%WCH_SELECTED_TOOLCHAIN_BIN%;%WCH_SELECTED_OPENOCD_BIN%;%PATH%"
set "WCH_TOOLCHAIN_BIN=%WCH_SELECTED_TOOLCHAIN_BIN%"
set "WCH_OPENOCD_BIN=%WCH_SELECTED_OPENOCD_BIN%"
echo Activated @TOOLCHAIN_NAME@
echo   compiler: %WCH_COMPILER%
"%WCH_COMPILER%" --version | findstr /B /C:"riscv"
