@rem Generated by wch-cmake.
@echo off
if "%MRS2_ROOT%"=="" set "MRS2_ROOT=C:\MounRiver\MounRiver_Studio2"
set "WCH_COMPONENT_ROOT=%MRS2_ROOT%\resources\app\resources\win32\components\WCH"
set "PATH=%WCH_COMPONENT_ROOT%\Toolchain\@TOOLCHAIN_NAME@\bin;%WCH_COMPONENT_ROOT%\OpenOCD\OpenOCD\bin;%PATH%"
echo Activated @TOOLCHAIN_NAME@ from %MRS2_ROOT%
