#!/usr/bin/env sh
# Generated by wch-cmake.

if [ -z "${MRS2_ROOT:-}" ]; then
    echo "MRS2_ROOT must point to a native WCH tool installation" >&2
    return 1 2>/dev/null || exit 1
fi

wch_component_root="$MRS2_ROOT/resources/app/resources/win32/components/WCH"
wch_toolchain_bin="$wch_component_root/Toolchain/@TOOLCHAIN_NAME@/bin"
wch_openocd_bin="$wch_component_root/OpenOCD/OpenOCD/bin"

if [ ! -d "$wch_toolchain_bin" ] || [ ! -d "$wch_openocd_bin" ]; then
    echo "Compatible WCH tools were not found below MRS2_ROOT=$MRS2_ROOT" >&2
    return 1 2>/dev/null || exit 1
fi

PATH="$wch_toolchain_bin:$wch_openocd_bin:$PATH"
export MRS2_ROOT PATH
echo "Activated @TOOLCHAIN_NAME@ from $MRS2_ROOT"
