# Generated by wch-cmake.
param(
    [string]$MrsRoot = $env:MRS2_ROOT
)

if (-not $MrsRoot) {
    $MrsRoot = "C:\MounRiver\MounRiver_Studio2"
}

$componentRoot = Join-Path $MrsRoot "resources\app\resources\win32\components\WCH"
$toolchainBin = Join-Path $componentRoot "Toolchain\@TOOLCHAIN_NAME@\bin"
$openOcdBin = Join-Path $componentRoot "OpenOCD\OpenOCD\bin"

if (-not (Test-Path -LiteralPath $toolchainBin)) {
    throw "WCH toolchain directory not found: $toolchainBin"
}
if (-not (Test-Path -LiteralPath $openOcdBin)) {
    throw "WCH OpenOCD directory not found: $openOcdBin"
}

$env:MRS2_ROOT = (Resolve-Path -LiteralPath $MrsRoot).Path
$env:PATH = "$toolchainBin;$openOcdBin;$env:PATH"
Write-Host "Activated @TOOLCHAIN_NAME@ from $env:MRS2_ROOT"
