# Generated by wch-cmake.
function(wch_finalize_firmware target)
    get_target_property(_wch_sources ${target} SOURCES)
    set(_wch_has_cxx OFF)
    foreach(_source IN LISTS _wch_sources)
        if(_source MATCHES "\\.(cc|cpp|cxx|c\\+\\+)$")
            set(_wch_has_cxx ON)
        endif()
    endforeach()
    if(_wch_has_cxx AND NOT WCH_STARTUP_HAS_CXX_INIT)
        target_sources(${target} PRIVATE
            "${CMAKE_CURRENT_SOURCE_DIR}/cmake/wch-cxx-runtime.c")
        target_link_options(${target} PRIVATE "-Wl,--wrap=main")
    endif()
endfunction()

function(wch_add_firmware target)
    foreach(_language C CXX ASM)
        set(CMAKE_${_language}_FLAGS_DEBUG "" CACHE STRING "" FORCE)
        set(CMAKE_${_language}_FLAGS_RELEASE "" CACHE STRING "" FORCE)
        set(CMAKE_${_language}_FLAGS_RELWITHDEBINFO "" CACHE STRING "" FORCE)
        set(CMAKE_${_language}_FLAGS_MINSIZEREL "" CACHE STRING "" FORCE)
    endforeach()

    add_executable(${target} ${WCH_SOURCES})
    set_target_properties(${target} PROPERTIES
        OUTPUT_NAME "${WCH_ARTIFACT_BASENAME}"
        SUFFIX ".elf"
    )

    # Finalize at the end of the directory so later target_sources() calls are
    # included in C++ runtime detection.
    cmake_language(EVAL CODE
        "cmake_language(DEFER CALL wch_finalize_firmware [[${target}]])")

    foreach(_include IN LISTS WCH_INCLUDE_DIRS)
        target_include_directories(${target} PRIVATE
            "$<$<COMPILE_LANGUAGE:C,CXX>:${CMAKE_CURRENT_SOURCE_DIR}/${_include}>")
    endforeach()
    foreach(_include IN LISTS WCH_ASM_INCLUDE_DIRS)
        target_include_directories(${target} PRIVATE
            "$<$<COMPILE_LANGUAGE:ASM>:${CMAKE_CURRENT_SOURCE_DIR}/${_include}>")
    endforeach()

    target_compile_options(${target} PRIVATE
        "$<$<COMPILE_LANGUAGE:C>:${WCH_C_FLAGS}>"
        "$<$<COMPILE_LANGUAGE:CXX>:${WCH_CXX_FLAGS}>"
        "$<$<COMPILE_LANGUAGE:ASM>:${WCH_ASM_FLAGS}>"
    )

    target_link_options(${target} PRIVATE
        ${WCH_LINK_FLAGS}
        "-T${CMAKE_CURRENT_SOURCE_DIR}/${WCH_LINKER_SCRIPT}"
        "-Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/${WCH_ARTIFACT_BASENAME}.map"
    )
    target_link_libraries(${target} PRIVATE ${WCH_LIBRARIES})

    set(_elf "$<TARGET_FILE:${target}>")
    set(_hex "${CMAKE_CURRENT_BINARY_DIR}/${WCH_ARTIFACT_BASENAME}.hex")
    set(_lst "${CMAKE_CURRENT_BINARY_DIR}/${WCH_ARTIFACT_BASENAME}.lst")
    add_custom_command(TARGET ${target} POST_BUILD
        COMMAND "${CMAKE_OBJCOPY}" -O ihex "${_elf}" "${_hex}"
        COMMAND "${CMAKE_COMMAND}"
                "-DWCH_OBJDUMP=${CMAKE_OBJDUMP}"
                "-DWCH_ELF=${_elf}"
                "-DWCH_LIST=${_lst}"
                -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/wch-objdump.cmake"
        COMMAND "${CMAKE_SIZE}" --format=berkeley "${_elf}"
        VERBATIM
    )
endfunction()
