# Generated by wch-cmake.
execute_process(
    COMMAND "${WCH_OBJDUMP}" --all-headers --demangle --disassemble -M xw "${WCH_ELF}"
    OUTPUT_FILE "${WCH_LIST}"
    RESULT_VARIABLE _wch_objdump_status
)
if(NOT _wch_objdump_status EQUAL 0)
    message(FATAL_ERROR "objdump failed with exit code ${_wch_objdump_status}")
endif()
