/* Generated by wch-cmake. Adds C++ static initialization to C-only WCH startup code. */
extern void __libc_init_array(void);
extern int __real_main(void);

void _init(void) __attribute__((weak));
void _fini(void) __attribute__((weak));

void _init(void)
{
}

void _fini(void)
{
}

int __wrap_main(void)
{
    __libc_init_array();
    return __real_main();
}
