# Generated by wch-cmake.
include_guard(GLOBAL)

include("${CMAKE_CURRENT_LIST_DIR}/wch-project.cmake")

if(NOT DEFINED ENV{MRS2_ROOT} OR "$ENV{MRS2_ROOT}" STREQUAL "")
    message(FATAL_ERROR
        "MRS2_ROOT is not set. Run the generated activation script or export "
        "MRS2_ROOT before configuring this project.")
endif()
file(TO_CMAKE_PATH "$ENV{MRS2_ROOT}" _wch_mrs2_root)
set(MRS2_ROOT "${_wch_mrs2_root}" CACHE PATH
    "MounRiver Studio 2 installation root" FORCE)

set(_wch_component_root
    "${MRS2_ROOT}/resources/app/resources/win32/components/WCH")
set(_wch_toolchain_bin
    "${_wch_component_root}/Toolchain/${WCH_TOOLCHAIN_NAME}/bin")

if(WIN32)
    set(_wch_exe ".exe")
else()
    set(_wch_exe "")
endif()

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER
    "${_wch_toolchain_bin}/${WCH_TOOL_PREFIX}gcc${_wch_exe}")
set(CMAKE_CXX_COMPILER
    "${_wch_toolchain_bin}/${WCH_TOOL_PREFIX}g++${_wch_exe}")
set(CMAKE_ASM_COMPILER
    "${_wch_toolchain_bin}/${WCH_TOOL_PREFIX}gcc${_wch_exe}")
set(CMAKE_AR
    "${_wch_toolchain_bin}/${WCH_TOOL_PREFIX}ar${_wch_exe}")
set(CMAKE_OBJCOPY
    "${_wch_toolchain_bin}/${WCH_TOOL_PREFIX}objcopy${_wch_exe}")
set(CMAKE_OBJDUMP
    "${_wch_toolchain_bin}/${WCH_TOOL_PREFIX}objdump${_wch_exe}")
set(CMAKE_SIZE
    "${_wch_toolchain_bin}/${WCH_TOOL_PREFIX}size${_wch_exe}")

foreach(_tool CMAKE_C_COMPILER CMAKE_CXX_COMPILER CMAKE_OBJCOPY CMAKE_SIZE)
    if(NOT EXISTS "${${_tool}}")
        message(FATAL_ERROR "Missing WCH tool: ${${_tool}}")
    endif()
endforeach()
